# Site settings
title: Ionshard
email: coreyling@ionshard.com
description: >
  Ionshard Developements is a organizational holding point for
  work done by Corey Ling.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ionshard.com" # the base hostname & protocol for your site
twitter_username: ionshard
github_username:  Ionshard
google_analytics: UA-XXXXX-X

# Build settings
markdown: kramdown
